name: Docker Image Build and Run CI
on: 
  schedule:
    - cron: "1 * * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: phiture/phiture_site_tests:latest
    - uses: addnab/docker-run-action@v3
      with:
        image: phiture/phiture_site_tests:latest
        run: python main.py
